package com.in28minutes.rest.webservices.restfulwebservices.jwt.resource;

import java.io.Serializable;

public class  JwtTokenRequest implements Serializable {
  
  private static final long serialVersionUID = -5616176897013108345L;

  private String username;
    private String password;
    
//   Token below generated by sending in body
//    {
//    "username": "in28minutes",
//    "password": "dummy"
//  }
//    to http://localhost:8080/authenticate
//    Where is this username/password set?
    
//    {
//    	"token": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJpbjI4bWludXRlcyIsImV4cCI6MTYzNDE0MDQzOCwiaWF0IjoxNjMzNTM1NjM4fQ.xP43WSUSWLUo76jW3pek92MfGb9na2CqxJqPyzdm4TM-hQYRcYCa8SD5FXfPrj-HlQl9WzyZ0O_1QscGo9tAlg"
//    }

    public JwtTokenRequest() {
        super();
    }

    public JwtTokenRequest(String username, String password) {
        this.setUsername(username);
        this.setPassword(password);
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
}

